"""Quants V1 VCP migration baseline.

This keeps a stable migration ID while the implementation is audited against
the source detector. It is intentionally separate from the user-facing VCP ID.
"""

from _quants_vcp import ENTRY_IDS, EXIT_IDS, QuantsLegacyVcpStrategy

META = {
    "id": "quants_vcp_legacy_v1",
    "name": "VCP 宽泛候选池（股票魔法师形态）",
    "version": "legacy-v1",
    "description": "盘后识别多段波动收缩与末段枢轴，输出观察、待突破、提前试探和放量突破等候选状态。默认冻结宽泛筛选口径，研究中的市场状态、入场与退出优化不会改变本候选池默认值。候选不等同于买入指令。",
    "tags": ["VCP", "股票魔法师形态", "宽泛候选池", "盘后筛选"],
    "strategy_role": "candidate_screener",
    "live_qualified": False,
    "asset_types": ["stock"],
    "timeframes": ["1d"],
    "chart_preview": {"enabled": False},
    "basic_filter": {"enabled": False},
    "params": [
        {"id": "trend_filter", "label": "趋势模板与周期收益", "type": "bool", "default": True},
        {
            "id": "rs_min",
            "label": "RS 百分位下限",
            "type": "float",
            "default": 85.0,
            "min": 0.0,
            "max": 100.0,
            "step": 1.0,
        },
        {
            "id": "distance_high_max",
            "label": "距年内高点上限",
            "type": "float",
            "default": 0.12,
            "min": 0.02,
            "max": 0.4,
            "step": 0.01,
        },
        {
            "id": "min_legs",
            "label": "最少收缩段",
            "type": "int",
            "default": 2,
            "min": 2,
            "max": 4,
            "step": 1,
        },
        {
            "id": "plan_stop_pct",
            "label": "计划止损比例",
            "type": "float",
            "default": 0.03,
            "min": 0.01,
            "max": 0.08,
            "step": 0.005,
        },
        {
            "id": "require_pivot_cross",
            "label": "仅首次上穿枢轴入场",
            "type": "bool",
            "default": False,
        },
        {
            "id": "allow_cheat",
            "label": "允许枢轴下方提前试探",
            "type": "bool",
            "default": True,
        },
        {
            "id": "breakout_volume_ratio_min",
            "label": "突破量比下限",
            "type": "float",
            "default": 1.25,
            "min": 1.0,
            "max": 3.0,
            "step": 0.05,
        },
        {
            "id": "breakout_volume_score_weight",
            "label": "突破量比排序权重",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 20.0,
            "step": 1.0,
        },
        {
            "id": "turnover_rank_weight",
            "label": "突破换手率排序权重",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 0.5,
            "step": 0.05,
        },
        {
            "id": "turnover_market_percentile_min",
            "label": "全市场换手率分位下限",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 100.0,
            "step": 5.0,
        },
        {
            "id": "roe_rank_weight",
            "label": "已公告ROE排序权重",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 0.5,
            "step": 0.05,
        },
        {
            "id": "short_scale_score_penalty",
            "label": "短尺度候选排序扣分",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 30.0,
            "step": 1.0,
        },
        {
            "id": "contraction_strength_rank_weight",
            "label": "收缩递减强度排序权重",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "short_scale_enabled",
            "label": "允许短周期VCP",
            "type": "bool",
            "default": True,
        },
        {
            "id": "breakout_close_location_min",
            "label": "突破K线收盘位置下限",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "prebreakout_pivot_closes_max",
            "label": "突破前20日枢轴上方收盘次数上限",
            "type": "int",
            "default": 20,
            "min": 0,
            "max": 20,
            "step": 1,
        },
        {
            "id": "market_breadth_percentile_lookback",
            "label": "市场广度滚动分位回看天数",
            "type": "int",
            "default": 0,
            "min": 0,
            "max": 504,
            "step": 21,
        },
        {
            "id": "market_breadth_percentile_min",
            "label": "市场广度滚动分位下限",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "market_breadth_percentile_max",
            "label": "市场广度滚动分位上限",
            "type": "float",
            "default": 1.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "exit_ma_days",
            "label": "趋势退出均线周期",
            "type": "int",
            "default": 20,
            "min": 5,
            "max": 60,
            "step": 5,
        },
        {
            "id": "market_breadth_ma20_min",
            "label": "市场MA20宽度下限",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "market_breadth_ma20_max",
            "label": "市场MA20宽度上限",
            "type": "float",
            "default": 1.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "market_equal_weight_return_lookback",
            "label": "市场等权收益回看天数",
            "type": "int",
            "default": 0,
            "min": 0,
            "max": 252,
            "step": 21,
        },
        {
            "id": "market_equal_weight_return_min",
            "label": "市场等权收益下限",
            "type": "float",
            "default": 0.0,
            "min": -0.5,
            "max": 0.5,
            "step": 0.01,
        },
        {
            "id": "a_share_dual_regime",
            "label": "A股VCP双阶段过滤",
            "type": "bool",
            "default": False,
        },
    ],
    "scoring": {},
    "order_by": "score",
    "descending": True,
    "limit": 100,
    "completed_daily_only": True,
    "realtime_supported": False,
}
EXECUTION_BACKEND = "matrix_native"
ENTRY_SIGNALS = list(ENTRY_IDS)
EXIT_SIGNALS = list(EXIT_IDS)
MATRIX_STRATEGY = QuantsLegacyVcpStrategy()
