"""VCP recovery breakout: a frozen, investable daily-bar strategy."""

from _quants_vcp import ENTRY_IDS, EXIT_IDS, QuantsLegacyVcpStrategy

META = {
    "id": "vcp_recovery_breakout",
    "research_only": True,
    "strategy_role": "research_variant",
    "name": "VCP 复苏突破(研究)",
    "version": "1.0.0",
    "description": (
        "在市场宽度处于早期复苏区间时, 选择趋势和相对强度领先、波动逐段收缩的股票, "
        "仅在首次放量突破枢轴后入场。当前仅保留为研究观察策略, 未取得实盘资格。"
    ),
    "tags": ["VCP", "趋势突破", "市场复苏", "研究观察"],
    "live_qualified": False,
    "asset_types": ["stock"],
    "timeframes": ["1d"],
    "chart_preview": {"enabled": False},
    "basic_filter": {
        "enabled": True,
        "price_min": 3.0,
        "price_max": 300.0,
        "market_cap_min": 1_000_000_000.0,
        "float_cap_min": None,
        "float_cap_max": None,
        "amount_min": 20_000_000.0,
        "amount_max": None,
        "turnover_min": None,
        "turnover_max": None,
        "exclude_st": True,
        "exclude_new_days": 30,
        "boards": ["沪主板", "深主板", "创业板", "科创板", "北交所"],
    },
    "params": [
        {"id": "trend_filter", "label": "趋势与周期收益过滤", "type": "bool", "default": True},
        {
            "id": "rs_min",
            "label": "相对强度百分位下限",
            "type": "float",
            "default": 85.0,
            "min": 0.0,
            "max": 100.0,
            "step": 1.0,
        },
        {
            "id": "distance_high_max",
            "label": "距年度高点上限",
            "type": "float",
            "default": 0.12,
            "min": 0.02,
            "max": 0.4,
            "step": 0.01,
        },
        {
            "id": "min_legs",
            "label": "最少收缩段数",
            "type": "int",
            "default": 2,
            "min": 2,
            "max": 4,
            "step": 1,
        },
        {
            "id": "contraction_ratio_max",
            "label": "相邻收缩深度上限比例",
            "type": "float",
            "default": 0.95,
            "min": 0.5,
            "max": 1.0,
            "step": 0.01,
        },
        {
            "id": "tightness_min",
            "label": "收缩质量下限",
            "type": "float",
            "default": 0.25,
            "min": 0.0,
            "max": 1.0,
            "step": 0.01,
        },
        {
            "id": "dry_volume_ratio_max",
            "label": "基底缩量比例上限",
            "type": "float",
            "default": 0.90,
            "min": 0.3,
            "max": 1.2,
            "step": 0.05,
        },
        {
            "id": "max_chase",
            "label": "突破追价上限",
            "type": "float",
            "default": 0.025,
            "min": 0.0,
            "max": 0.1,
            "step": 0.005,
        },
        {
            "id": "plan_stop_pct",
            "label": "计划止损比例",
            "type": "float",
            "default": 0.03,
            "min": 0.01,
            "max": 0.08,
            "step": 0.005,
        },
        {"id": "require_pivot_cross", "label": "仅首次上穿枢轴入场", "type": "bool", "default": True},
        {"id": "allow_cheat", "label": "允许枢轴下方提前试探", "type": "bool", "default": False},
        {
            "id": "breakout_volume_ratio_min",
            "label": "突破量比下限",
            "type": "float",
            "default": 1.25,
            "min": 1.0,
            "max": 3.0,
            "step": 0.05,
        },
        {
            "id": "breakout_volume_score_weight",
            "label": "突破量比排序权重",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 20.0,
            "step": 1.0,
        },
        {
            "id": "breakout_close_location_min",
            "label": "突破 K 线收盘位置下限",
            "type": "float",
            "default": 0.0,
            "min": 0.0,
            "max": 1.0,
            "step": 0.05,
        },
        {
            "id": "exit_ma_days",
            "label": "趋势退出均线周期",
            "type": "int",
            "default": 20,
            "min": 5,
            "max": 60,
            "step": 5,
        },
        {
            "id": "market_breadth_ma20_min",
            "label": "市场 MA20 宽度下限",
            "type": "float",
            "default": 0.30,
            "min": 0.0,
            "max": 1.0,
            "step": 0.01,
        },
        {
            "id": "market_breadth_ma20_max",
            "label": "市场 MA20 宽度上限",
            "type": "float",
            "default": 0.35,
            "min": 0.0,
            "max": 1.0,
            "step": 0.01,
        },
        {
            "id": "legacy_semantics",
            "label": "旧版数值取整语义",
            "type": "bool",
            "default": False,
        },
    ],
    "scoring": {},
    "order_by": "score",
    "descending": True,
    "limit": 100,
    "completed_daily_only": True,
    "realtime_supported": False,
}

EXECUTION_BACKEND = "matrix_native"
ENTRY_SIGNALS = list(ENTRY_IDS)
EXIT_SIGNALS = list(EXIT_IDS)
STOP_LOSS = -0.03
MAX_HOLD_DAYS = 40
MATRIX_STRATEGY = QuantsLegacyVcpStrategy()
